export const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    id: 'plan_3m',
    name: 'Quarterly Growth',
    durationMonths: 3,
    durationLabel: '3 Months',
    price: 4999,
    originalPrice: 5999,
    savingsPercent: 16,
    isPopular: false,
    tagline: 'Ideal for independent dealers testing property velocity.',
    features: [
      'Unmasked Phone Number on all listings',
      'Direct WhatsApp inquiry button for buyers',
      'Unlimited property listings',
      'Instant lead notification alerts',
      'Standard search placement',
      'Basic inquiry dashboard',
    ],
  },
  {
    id: 'plan_6m',
    name: 'Half-Year Momentum',
    durationMonths: 6,
    durationLabel: '6 Months',
    price: 8999,
    originalPrice: 11999,
    savingsPercent: 25,
    isPopular: true,
    tagline: 'Best balance of sustained buyer visibility and cost efficiency.',
    features: [
      'Unmasked Phone Number on all listings',
      'Direct WhatsApp inquiry button for buyers',
      'Unlimited property listings',
      'Priority lead notifications',
      'Featured placement in locality searches',
      'Advanced lead analytics & conversion CRM',
      'Dedicated support line',
    ],
  },
  {
    id: 'plan_12m',
    name: 'Annual Dominance',
    durationMonths: 12,
    durationLabel: '12 Months',
    price: 14999,
    originalPrice: 23999,
    savingsPercent: 37,
    isPopular: false,
    tagline: 'Maximum ROI for established real estate agencies and top brokers.',
    features: [
      'Unmasked Phone Number on all listings',
      'Direct WhatsApp inquiry button for buyers',
      'Unlimited property listings',
      'Top-tier search priority & home page spotlight',
      'Verified Dealer badge across all properties',
      'Instant SMS & WhatsApp lead delivery',
      'Unlimited CRM inquiries export (CSV/Excel)',
      'Quarterly performance report from account manager',
    ],
  },
];
